#!/usr/bin/env python3
import argparse
import json
import os
import random
import re
import subprocess
from pathlib import Path


KEYWORDS = [
    "channel(",
    "unbounded_channel",
    "sync_channel",
    "broadcast::channel",
    "oneshot::channel",
    "watch::channel",
    "flume::",
    "crossbeam_channel",
    "async_channel",
]


GENERATED_MARKERS = [
    "@generated",
    "automatically generated",
    "auto-generated",
    "autogenerated",
    "generated by",
    "code generated",
]

EXCLUDED_PATH_RE = re.compile(
    r"(^|/)(test|tests|example|examples|bench|benches|mock|mocks|fixture|fixtures)(/|_)"
    r"|_test\.rs$|_tests\.rs$|test\.rs$|tests\.rs$"
)

SKIP_DIRS = {
    ".git",
    "target",
    "node_modules",
    ".direnv",
    ".idea",
    ".vscode",
}


def line_count(text: str) -> int:
    if not text:
        return 0
    return text.count("\n") + (0 if text.endswith("\n") else 1)


def line_count_and_text(path: Path) -> tuple[int, str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    return line_count(text), text


def git(repo: Path, args: list[str]) -> str:
    return subprocess.check_output(
        ["git", "-C", str(repo), *args],
        text=True,
        stderr=subprocess.PIPE,
    )


def git_file_text(repo: Path, commit: str, rel: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(repo), "show", f"{commit}:{rel}"],
        stderr=subprocess.PIPE,
    ).decode("utf-8", errors="ignore")


def collect_candidates(repo: Path, max_lines: int) -> list[tuple[str, int]]:
    candidates = []
    for dirpath, dirnames, filenames in os.walk(repo):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for filename in filenames:
            if not filename.endswith(".rs"):
                continue

            path = Path(dirpath) / filename
            rel = path.relative_to(repo).as_posix()
            if EXCLUDED_PATH_RE.search(rel):
                continue

            try:
                lines, text = line_count_and_text(path)
            except OSError:
                continue

            if lines > max_lines:
                continue
            lowered_prefix = text[:2000].lower()
            if any(marker in lowered_prefix for marker in GENERATED_MARKERS):
                continue
            if not any(keyword in text for keyword in KEYWORDS):
                continue

            candidates.append((rel, lines))

    return sorted(candidates)


def collect_candidates_at_commit(repo: Path, commit: str, max_lines: int) -> list[tuple[str, int]]:
    try:
        git(repo, ["cat-file", "-e", f"{commit}^{{commit}}"] )
        tree = git(repo, ["ls-tree", "-r", "--name-only", commit])
    except subprocess.CalledProcessError as exc:
        raise SystemExit(
            f"Could not read commit {commit!r} in {repo}: {exc.stderr.strip()}"
        )

    candidates = []
    for rel in tree.splitlines():
        if not rel.endswith(".rs"):
            continue
        if EXCLUDED_PATH_RE.search(rel):
            continue
        if any(part in SKIP_DIRS for part in rel.split("/")):
            continue

        try:
            text = git_file_text(repo, commit, rel)
        except subprocess.CalledProcessError:
            continue

        lines = line_count(text)
        if lines > max_lines:
            continue
        lowered_prefix = text[:2000].lower()
        if any(marker in lowered_prefix for marker in GENERATED_MARKERS):
            continue
        if not any(keyword in text for keyword in KEYWORDS):
            continue

        candidates.append((rel, lines))

    return sorted(candidates)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sample Rust files containing message-passing channel keywords."
    )
    parser.add_argument(
        "repo",
        nargs="?",
        default=".",
        help="Repository root. Defaults to current directory.",
    )
    parser.add_argument(
        "--commit",
        help="Git commit to sample from. When set, files are read from that commit instead of the working tree.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed used for reproducible sampling.",
    )
    parser.add_argument(
        "--sample-size",
        type=int,
        default=5,
        help="Number of files to sample. If fewer candidates exist, all candidates are selected.",
    )
    parser.add_argument(
        "--max-lines",
        type=int,
        default=6000,
        help="Exclude files above this line count.",
    )
    parser.add_argument(
        "--list-candidates",
        action="store_true",
        help="Print the full filtered candidate list instead of sampling.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print sampling metadata and selected files as JSON.",
    )
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    candidates = (
        collect_candidates_at_commit(repo, args.commit, args.max_lines)
        if args.commit
        else collect_candidates(repo, args.max_lines)
    )

    rng = random.Random(args.seed)
    actual_sample_size = min(args.sample_size, len(candidates))
    sampled = rng.sample(candidates, actual_sample_size) if actual_sample_size else []

    if args.json:
        payload = {
            "repo": str(repo),
            "selection_method": "filtered_uniform_random_file_sample",
            "source": "git_commit" if args.commit else "working_tree",
            "commit": args.commit,
            "candidate_query_keywords": KEYWORDS,
            "excluded_path_pattern": EXCLUDED_PATH_RE.pattern,
            "excluded_dirs": sorted(SKIP_DIRS),
            "generated_markers": GENERATED_MARKERS,
            "seed": args.seed,
            "requested_sample_size": args.sample_size,
            "actual_sample_size": actual_sample_size,
            "candidate_count": len(candidates),
            "max_file_lines": args.max_lines,
            "selected_files": [
                {"file": rel, "line_count": lines} for rel, lines in sampled
            ],
        }
        if args.list_candidates:
            payload["candidates"] = [
                {"file": rel, "line_count": lines} for rel, lines in candidates
            ]
        print(json.dumps(payload, indent=2))
        return

    print(f"repo={repo}")
    print(f"source={'git_commit' if args.commit else 'working_tree'}")
    if args.commit:
        print(f"commit={args.commit}")
    print(f"candidate_count={len(candidates)}")
    print(f"seed={args.seed}")
    print(f"requested_sample_size={args.sample_size}")
    print(f"actual_sample_size={actual_sample_size}")
    print(f"max_file_lines={args.max_lines}")

    if args.list_candidates:
        print("candidates:")
        for rel, lines in candidates:
            print(f"{lines}\t{rel}")
        return

    print("sampled_files:")
    for rel, lines in sampled:
        print(f"{lines}\t{rel}")


if __name__ == "__main__":
    main()
